;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                    HW5                                     ;
;                   Servomotor Interface specific functions                  ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the specific functions of the HW5 servomotor interface 
; system. It include the following functions:
;       InitServoGPT       - Initialize PWM timer for servomotor PWM input
;       SetServo           - set servomotor position to specific angle
;       GetServo           - return the current position of servo in degrees (-90° ~ 90°)
;       ReleaseServo       - turn off the servo for manual setting
; Revision History:
;       12/10/25     Li-Yu Chu             initial revision
;       12/11/25     Li-Yu Chu             update GetServo
;       12/12/25     Li-Yu Chu             update comments


; local include files
        .include  "CPUreg.inc"
        .include  "GPIOreg.inc"
        .include  "IOCreg.inc"
        .include  "GPTreg.inc"
        .include  "ADCreg.inc"
        .include  "constant.inc"
        .include  "macro.inc"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; data
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .data
        ;servomotor timer initialization
        .def    InitServoGPT

        ;exported servomotor functions
        .global SetServo                ;set servomotor position to specific angle 
        .global GetServo                ;return the current position of servo in degrees
        .global ReleaseServo            ;turn off the servo for manual setting
        
        ;LCD function
        .ref    Display                 ;display decimal string in GetServo
        .ref    ClearDisplay            ;clear the LCD output
        
        ;Invalid string
        .ref    InvalidString

        .align 4
GetServoString: .space  BYTES_PER_WORD  ;the string storing wrapped angle returned by GetServo

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; code
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .text

; InitServoGPT
;
; Description:       This function initializes GPT1A for PWM output to servomotor.
;
; Operation:         GPT1A is configured to a 50Hz PWM mode 16-bit timer with inverted 
;                    PWM output. Notice that the timer count requires 48MHz / 50Hz
;                    = 960k > 2^16, so we store the lower 16 bits to interval load register,
;                    and move upper 8 bits to pre-scaler. Then, we reset the corresponding
;                    match register to 0 to reset output duty cycle to 0. Finally, GPT1A
;                    is enabled with inverted PWM output.
;
; Arguments:         None.
; Return Value:      None.
;
; Local Variables:   None.
; Shared Variables:  None.
; Global Variables:  None.
;
; Input:             None.
; Output:            DIO3 - the PWM output generated by GPT1A
;
; Error Handling:    None.
;
; Algorithms:        None.
; Data Structures:   None.
;
; Registers Changed: R0, R1
; Stack Depth:       0 words
;
; Known Bugs:        None.
; Limitation:        None.
;
; Revision History:  12/10/25   Li-Yu Chu       initial revision

InitServoGPT:

GPT1AConfig:                                            ;configure timer 1 as a PWM down counter
        
        MOV32   R1, GPT1_BASE_ADDR                      ;get GPT1 base address
        STREG   GPT_CFG_16x2, R1, GPT_CFG_OFF           ;setup one 32-bit timer
        STREG   GPT1A_MODE, R1, GPT_TAMR_OFF            ;set timer A mode

        STREG   PWM_ILR, R1, GPT_TAILR_OFF              ;set 32-bit timer count
        STREG   (PWM_ILR >> 16), R1, GPT_TAPR_OFF       ;set 32-bit timer pre-scale count
        STREG   RESET_MATCHR, R1, GPT_TAMATCHR_OFF      ;reset duty cycle to 0
        STREG   RESET_MATCHR, R1, GPT_TAPMR_OFF         ;reset duty cycle to 0 for pre-scale
        STREG   GPT_CTL_TAEN_PWM_INV, R1, GPT_CTL_OFF   ;enable GPT1A

        BX      LR

; SetServo
;
; Description:       This function sets the servomotor position to a specified angle
;                    passed in R0 by updating the PWM duty cycle of GPT1A.
;
; Operation:         First, it validates the input angle to ensure it lies within [-90°, +90°].
;                    If the input is invalid, it outputs "Invalid" on LCD by Display and return.
;                    If the input is valid, it converts the angle into a corresponding PWM match
;                    value using a linear mapping from angle to duty cycle. Finally, it updates 
;                    GPT1A match and prescaler registers to change the PWM output.
;
; Arguments:         R0 - the desired servomotor angle in degrees. The positive angle is measured
;                         counterclockwise, and vice versa. The valid range for servomotor position
;                         is [-90°, +90°], and the angle resolution is 1 degree.
; Return Value:      None.
;
; Local Variables:   None.
; Shared Variables:  None.
; Global Variables:  None.               
;
; Input:             None.
; Output:            DIO3 - GPT1A PWM duty cycle updated to drive servomotor
;
; Error Handling:    If the input angle is out of range, "Invalid" is displayed on the LCD and no
;                    PWM update occurs.
;
; Algorithms:        The duty cycle for a specific position is determined by a linear mapping,
;                    which is PWM = ZERO_POS_MATCHR + (angle × ONE_DEGREE_MATCHR)
; Data Structures:   None.
;
; Registers Changed: flags, R0, R1, R2, R5
; Stack Depth:       3 words
;
; Known Bugs:        None.
; Limitation:        The input argument should be an integer valued angle, which is limited by
;                    PWM match resolution.
;
; Revision History:  12/10/25   Li-Yu Chu      initial revision
;                    12/12/25   Li-Yu Chu      update comments

SetServo:

CheckSetUpperbound:
                                                ;check upper bound first
        CMP     R0, #ANGLE_UPPER                ;if R0 is larger than 90°
        BGT     InvalidSet                      ;if invalid value is set, display "invalid" on LCD
        ;BLT    CheckSetLowerbound              ;if not, check lower bound

CheckSetLowerbound:

        MOV32   R1, ANGLE_LOWER
        CMP     R0, R1                          ;if R0 is lower than -90°
        BLT     InvalidSet                      ;if invalid value is set, display "invalid" on LCD
        ;BGE    StartSetServo                   ;if all passed, finish checking

StartSetServo:
        
        MOV32   R1, ZERO_POS_MATCHR             ;get the duty cycle for 0 degree
        MOV32   R5, ONE_DEGREE_MATCHR           ;get duty cycle difference for 1°
        MLA     R2, R0, R5, R1                  ;compute the offset duty cycle according to input argument
                                                ;R2 = ZERO_POS + angle × ONE_DEGREE_MATCHR
                                                ;R2 = 72k + angle × 533 

        MOV32   R1, GPT1_BASE_ADDR              ;get base address of GPT1 timer
        STR     R2, [R1, #GPT_TAMATCHR_OFF]     ;store duty cycle for GPT1A
        ASR     R2, R2, #16                     ;retrieve the upper bits for pre-scaler
        STR     R2, [R1, #GPT_TAPMR_OFF]        ;store duty cycle pre-scaler for GPT1A
        
        BX      LR                              ;done so return

InvalidSet:
                                                ;handle invalid servo angle input
                                                ;no PWM output changed, and Display "Invalid"
        PUSH    {R3 - R4, LR}                   ;save registers for test table and return
        MOVA    R2, InvalidString               ;load address of "Invalid" string
        MOV     R0, #ROW_LOW                    ;set output start position to row = 0, col = 0
        MOV     R1, #COL_LOW
        LDRB    R4, [R2], #1                    ;load "Invalid" string length
        BL      ClearDisplay                    ;clear previous LCD outputs
        BL      Display                         ;display "Invalid" string

        POP     {R3 - R4, LR}                   ;restore registers
        BX      LR                              ;done so return

; GetServo
;
; Description:       This function reads the ADC data corresponding to the servo position
;                    from servomotor's analog feedback input and converts the data into a
;                    servo angle in degrees. The angle is returned through R0, and it is 
;                    also displayed at the original position (row = 0, column = 0) on LCD.
;
; Operation:         First, it manually triggers an ADC conversion. Then, it polls the ADC
;                    FIFO flag until conversion data is available (FIFO is not empty).
;                    Knowing that data are ready, it reads ADC result and linearly map it 
;                    to a servo angle, and clamps the result to [-90°, +90°] Then, it converts
;                    the angle into a 3-character ASCII decimal string stored in GetServoString
;                    , with the first character indicating positive or negative angle. Finally,
;                    the required arguments are passed into Display, and it displays the string
;                    on the LCD, and return the numeric angle in R0.
;
; Arguments:         None.
; Return Value:      R0 - the current angle for the servomotor in degrees. An angle of zero (0)
;                         indicates the stepper motor is in the "home" position and angles are
;                         measured counterclockwise. The value returned will always be
;                         between [-90°, +90°] inclusively.
;
; Local Variables:   GetServoString -  a 4-byte variable containing a 3-byte string with
;                                      each byte storing a decimal character, and the 
;                                      first byte is always the string length 3. The
;                                      pointer for this string will be the input argument
;                                      for Display(), which is passed by R2.
; Shared Variables:  None.
; Global Variables:  None.
;
; Input:             DIO23 - analog feedback input from servomotor
; Output:            Current angle is displayed on LCD.
;
; Error Handling:    None.
;
; Algorithms:        The process to receive data from ADC FIFO is a polling-based ADC read. Also,
;                    the conversion from ADC data to angle is calibrated by clamping and linear
;                    mapping. Finally, the conversion of angle to ASCII decimal string is done
;                    by unsigned division (UDIV) to compute quotient, and multiply– subtract
;                    (MLS) for remainder.
; Data Structures:   None.
;
; Registers Changed: flags, R0, R1, R2, R5, R6
; Stack Depth:       3 words
;
; Known Bugs:        None.
; Limitation:        The computed angle has a maximum 1 degree error compared with theoretical
;                    values. 
;
; Revision History:  12/11/25   Li-Yu Chu      initial revision
;                    12/12/25   Li-Yu Chu      update comments

GetServo:

        PUSH    {R3, R4, LR}                    ;store registers
        MOV32   R1, AUX_ANAIF_BASE_ADDR         ;get ADC interface base address
        STREG   ADCTRIG_START, R1, ADCTRIG_OFF  ;manually trigger ADC conversion

WaitADCFIFO:

        LDR     R2, [R1, #ADCFIFOSTAT_OFF]      ;load FIFO flag status
        CMP     R2, #ADCFIFO_EMPTY              ;check if FIFO is empty
        BEQ     WaitADCFIFO                     ;if FIFO is empty, wait until it's not
        ;BNE    PopADCFIFO                      ;if FIFO is not empty, data is ready

PopADCFIFO:

        LDR     R2, [R1, #ADCFIFO_OFF]          ;read ADC conversion result

LinearMap:

        CMP     R2, #DATA_LOWER                 ;check ADC data lower bound
        BLE     LowerBound                      ;if smaller, clamp result to -90°

        MOV     R3, #DATA_UPPER                 
        CMP     R2, R3                          ;check ADC data upper bound
        BGE     UpperBound                      ;if bigger, clamp result to +90°

                                                ;angle = (data - offset) / scaling factor
                                                ;angle = (data - 255) / 15
        MOV     R1, #DATA_TO_ANGLE              ;R1 = scaling factor
        SUB     R2, #DATA_LOWER                 ;R2 = data - offset ADC value
        UDIV    R0, R2, R1                      ;convert data to angle
        SUB     R0, #ANGLE_OFFSET               ;shift angle to signed range
        B       EndGetServo
        
LowerBound:
                                                ;if ADC data is too small
        MOV32   R0, ANGLE_LOWER                 ;clamp angle to -90°
        B       EndGetServo                     ;prepare to display

UpperBound:
                                                ;if ADC data is too big
        MOV32   R0, ANGLE_UPPER                 ;clamp angle to +90°
        ;B      EndGetServo                     ;prepare to display

EndGetServo:

                                        ;conversion of angle to ASCII decimal string
        MOVA    R2, GetServoString      ;get address of output buffer 
        MOV     R6, R0                  ;save numeric angle (return value)

        MOV     R1, #ANGLE_STRING_LENGTH ;store string length 3 to first byte
        STRB    R1, [R2]                
                                        ;compute sign of string
        CMP     R0, #0                  
        BGE     StorePositive           ;if angle >= 0, sign = '+'
        ;BLT    StoreNegative           ;if angle < 0, sign = '-'

StoreNegative:

        MOV     R1, #'-'
        STRB    R1, [R2, #1]            ;store '-' to second byte
        RSB     R0, R0, #0              ;convert negative value to positive one
                                        ;for unsigned division
        B       ConvertAngle            ;start converting angle

StorePositive:

        MOV     R1, #'+'
        STRB    R1, [R2, #1]            ;store '+' to second byte
        ;B      ConvertAngle

ConvertAngle:

                                        ;compute tens digit of the string
        MOV     R3, #TEN                ;quotient = angle / 10
        UDIV    R1, R0, R3              

        ADD     R4, R1, #NUM_ASCII_OFF  ;convert digit to ASCII
        STRB    R4, [R2, #2]            ;store tens digit

                                        ;compute remainder
        MLS     R0, R3, R1, R0          ;remainder = angle - (10 * digit10)

                                        ;compute ones digit of the string
                                        ;already found as remainder
        ADD     R0, R0, #'0'            ;convert digit to ASCII
        STRB    R0, [R2, #3]            ;store ones digit
        ;B      CallDisplay

CallDisplay:

        MOV32   R0, ROW_LOW             ;set display position row = 0, column = 0
        MOV32   R1, COL_LOW
        LDRB    R4, [R2], #1            ;load string length (= 3)
        BL      ClearDisplay            ;clear previous LCD outputs
        BL      Display                 ;write GetServoString to LCD

        MOV     R0, R6                  ;restore numeric angle for return

        POP     {R3, R4, LR}            ;restore registers

        BX      LR                      ;done so return

; ReleaseServo
;
; Description:       This function turns off the servomotor for manual setting.
;
; Operation:         It resets GPT1A match and prescaler match registers in order to disable
;                    the servomotor for manual repositioning. The PWM output remains enabled
;                    but produces no active pulse.
;
; Arguments:         None.
; Return Value:      None.
;
; Local Variables:   None.
; Shared Variables:  None.
; Global Variables:  None.
;
; Input:             None.
; Output:            DIO3 - Servomotor PWM signal effectively disabled.
;
; Error Handling:    None.
;
; Algorithms:        None.
; Data Structures:   None.
;
; Registers Changed: R0, R1
; Stack Depth:       0 words
;
; Known Bugs:        None.
; Limitation:        None.
;
; Revision History:  12/10/25   Li-Yu Chu      initial revision
;                    12/12/25   Li-Yu Chu      update comments

ReleaseServo:

        MOV32   R1, GPT1_BASE_ADDR                     ;get base address of GPT1 timer
        STREG   RESET_MATCHR, R1, GPT_TAMATCHR_OFF     ;reset duty cycle to 0 for servo
        STREG   RESET_MATCHR, R1, GPT_TAPMR_OFF                

        BX      LR

        .end